// ═══════════════════════════════════════
// DATA CONSTANTS & HELPERS
// ═══════════════════════════════════════
export const LANGUAGES = [
  { code:"fr", label:"Français", flag:"🇫🇷" },{ code:"en", label:"English", flag:"🇬🇧" },
  { code:"ar", label:"العربية", flag:"🇲🇦" },{ code:"es", label:"Español", flag:"🇪🇸" },
  { code:"pt", label:"Português", flag:"🇵🇹" },{ code:"zh", label:"中文", flag:"🇨🇳" },
];
export const PLACEHOLDERS = { fr:"Posez votre question...", en:"Ask your question...", ar:"...اطرح سؤالك", es:"Haz tu pregunta...", pt:"Faça sua pergunta...", zh:"请输入问题..." };
export const QUICK_TOPICS = {
  fr:["🏟️ Stades","🚇 Transport","🍜 Restaurants","🏨 Hôtels","🚑 Urgences","🕌 Culture","☀️ Météo"],
  en:["🏟️ Stadiums","🚇 Transport","🍜 Food","🏨 Hotels","🚑 Emergency","🕌 Culture","☀️ Weather"],
  ar:["🏟️ ملاعب","🚇 نقل","🍜 مطاعم","🏨 فنادق","🚑 طوارئ","🕌 ثقافة","☀️ طقس"],
  es:["🏟️ Estadios","🚇 Transporte","🍜 Comida","🏨 Hoteles","🚑 Urgencias","🕌 Cultura","☀️ Clima"],
  pt:["🏟️ Estádios","🚇 Transporte","🍜 Comida","🏨 Hotéis","🚑 Urgências","🕌 Cultura","☀️ Tempo"],
  zh:["🏟️ 球场","🚇 交通","🍜 美食","🏨 酒店","🚑 急救","🕌 文化","☀️ 天气"],
};
export const SYSTEM_PROMPTS = {
  fr:`Tu es MoundiGuide, assistant IA du Mondial 2030. Réponds en 3-5 phrases MAX. Direct, pratique. Emojis.`,
  en:`You are MoundiGuide, 2030 World Cup AI assistant. 3-5 sentences MAX. Direct, practical. Emojis.`,
  ar:`أنت MoundiGuide مساعد كأس العالم 2030. 3 جمل كحد أقصى. مباشر وعملي.`,
  es:`Eres MoundiGuide, asistente Mundial 2030. 3 frases MAX. Directo. Emojis.`,
  pt:`Você é MoundiGuide, assistente Copa 2030. 3 frases MAX. Direto. Emojis.`,
  zh:`你是MoundiGuide，2030世界杯助手。最多3句。直接。表情。`,
};
export const WELCOME = { fr:"⚽ Bienvenue ! Posez-moi une question sur le Mondial 2030.", en:"⚽ Welcome! Ask about the 2030 World Cup.", ar:"⚽ مرحباً! اسألني عن المونديال.", es:"⚽ ¡Hola! Pregunta sobre el Mundial.", pt:"⚽ Olá! Pergunte sobre a Copa.", zh:"⚽ 你好！问我世界杯相关问题。" };
export const STADIUMS = [
  { city:"Casablanca", name:"Grand Stade Hassan II", cap:"115 000", lat:33.57, lng:-7.59 },
  { city:"Rabat",      name:"Complexe Moulay Abdallah", cap:"52 000", lat:33.96, lng:-6.86 },
  { city:"Marrakech",  name:"Grand Stade de Marrakech", cap:"45 000", lat:31.62, lng:-8.01 },
  { city:"Tanger",     name:"Grand Stade de Tanger", cap:"65 000", lat:35.74, lng:-5.83 },
  { city:"Agadir",     name:"Stade d'Agadir", cap:"45 000", lat:30.38, lng:-9.53 },
  { city:"Fès",        name:"Nouveau Stade de Fès", cap:"50 000", lat:34.02, lng:-5.01 },
];
export const FIFA_RANKINGS = [
  {r:1,t:"Spain",f:"🇪🇸",p:1867,c:"="},{r:2,t:"Argentina",f:"🇦🇷",p:1849,c:"="},{r:3,t:"France",f:"🇫🇷",p:1843,c:"="},
  {r:4,t:"England",f:"🏴󠁧󠁢󠁥󠁮󠁧󠁿",p:1797,c:"="},{r:5,t:"Brazil",f:"🇧🇷",p:1775,c:"="},{r:6,t:"Portugal",f:"🇵🇹",p:1756,c:"="},
  {r:7,t:"Netherlands",f:"🇳🇱",p:1747,c:"="},{r:8,t:"Morocco",f:"🇲🇦",p:1733,c:"up"},{r:9,t:"Belgium",f:"🇧🇪",p:1729,c:"dn"},
  {r:10,t:"Germany",f:"🇩🇪",p:1713,c:"="},{r:11,t:"Croatia",f:"🇭🇷",p:1701,c:"="},{r:12,t:"Senegal",f:"🇸🇳",p:1694,c:"up"},
  {r:13,t:"Italy",f:"🇮🇹",p:1690,c:"dn"},{r:14,t:"Colombia",f:"🇨🇴",p:1679,c:"="},{r:15,t:"USA",f:"🇺🇸",p:1665,c:"dn"},
  {r:16,t:"Mexico",f:"🇲🇽",p:1658,c:"dn"},{r:17,t:"Uruguay",f:"🇺🇾",p:1650,c:"="},{r:18,t:"Switzerland",f:"🇨🇭",p:1637,c:"="},
  {r:19,t:"Japan",f:"🇯🇵",p:1625,c:"="},{r:20,t:"Iran",f:"🇮🇷",p:1612,c:"up"},
];
export const MATCHES = [
  {ph:"G",d:"15 Jun",tm:"18:00",a:"🇲🇦 Maroc",b:"Brésil 🇧🇷",c:"Casablanca"},
  {ph:"G",d:"16 Jun",tm:"21:00",a:"🇪🇸 Espagne",b:"Argentine 🇦🇷",c:"Rabat"},
  {ph:"G",d:"17 Jun",tm:"18:00",a:"🇵🇹 Portugal",b:"France 🇫🇷",c:"Marrakech"},
  {ph:"G",d:"20 Jun",tm:"21:00",a:"🇲🇦 Maroc",b:"Allemagne 🇩🇪",c:"Tanger"},
  {ph:"G",d:"21 Jun",tm:"18:00",a:"🇪🇸 Espagne",b:"Japon 🇯🇵",c:"Agadir"},
  {ph:"G",d:"22 Jun",tm:"21:00",a:"🇵🇹 Portugal",b:"Mexique 🇲🇽",c:"Fès"},
  {ph:"8",d:"1 Jul", tm:"18:00",a:"1A",b:"2B",c:"Casablanca"},
  {ph:"8",d:"2 Jul", tm:"21:00",a:"1B",b:"2A",c:"Rabat"},
  {ph:"Q",d:"5 Jul", tm:"21:00",a:"W1",b:"W2",c:"Marrakech"},
  {ph:"Q",d:"6 Jul", tm:"21:00",a:"W3",b:"W4",c:"Casablanca"},
  {ph:"S",d:"9 Jul", tm:"21:00",a:"SF1",b:"SF2",c:"Casablanca"},
  {ph:"S",d:"10 Jul",tm:"21:00",a:"SF3",b:"SF4",c:"Rabat"},
  {ph:"F",d:"13 Jul",tm:"21:00",a:"🏆 Finale",b:"⚽",c:"Casablanca"},
];
export const NEWS = [
  {d:"12 Avr",t:"Grand Stade Hassan II : 95% de construction",tg:"Infra",tc:"#00913F"},
  {d:"10 Avr",t:"Plan de mobilité pour les 6 villes hôtes",tg:"Transport",tc:"#1A56DB"},
  {d:"8 Avr", t:"FIFA confirme 48 équipes qualifiées",tg:"FIFA",tc:"#E41C3A"},
  {d:"5 Avr", t:"Billetterie en ligne ouvrira en janvier 2029",tg:"Billets",tc:"#F0B429"},
  {d:"3 Avr", t:"YallaVamos : 20 000 bénévoles recherchés",tg:"Bénévol.",tc:"#7C3AED"},
];
export const CURRENCIES = [{c:"EUR",s:"€"},{c:"USD",s:"$"},{c:"GBP",s:"£"},{c:"BRL",s:"R$"},{c:"JPY",s:"¥"}];
export const INFO_ITEMS = [{i:"🚨",l:"Police",v:"19"},{i:"🚑",l:"SAMU",v:"15"},{i:"🚒",l:"Pompiers",v:"15"},{i:"💱",l:"Monnaie",v:"MAD"},{i:"🔌",l:"220V",v:"C,E"},{i:"🕐",l:"Fuseau",v:"GMT+1"},{i:"📱",l:"Indicatif",v:"+212"},{i:"💧",l:"Eau",v:"Bouteille"}];
export const DARIJA = [{d:"Salam",t:{fr:"Bonjour",en:"Hello",ar:"مرحبا",es:"Hola"}},{d:"Beshhal?",t:{fr:"Combien?",en:"How much?",ar:"بكم؟",es:"¿Cuánto?"}},{d:"Shukran",t:{fr:"Merci",en:"Thanks",ar:"شكرا",es:"Gracias"}},{d:"Fin kayn?",t:{fr:"Où est?",en:"Where?",ar:"فين؟",es:"¿Dónde?"}},{d:"Mezyan",t:{fr:"Bien",en:"Good",ar:"مزيان",es:"Bien"}}];
export const TICKET_CATS = [
  {cat:"Category 1",price:"990 USD",color:"#F0B429",desc:"Best seats — behind the goal or central stands",icon:"⭐"},
  {cat:"Category 2",price:"605 USD",color:"#E41C3A",desc:"Upper lateral stands with excellent view",icon:"🎟️"},
  {cat:"Category 3",price:"385 USD",color:"#1A56DB",desc:"Standard seats — great atmosphere",icon:"🏟️"},
  {cat:"Category 4",price:"110 USD",color:"#00913F",desc:"Host nation residents price (MAD equiv.)",icon:"🇲🇦"},
];
export const CITIES = [
  {city:"Casablanca",img:"/casablanca.jpg",      flag:"🌊"},
  {city:"Rabat",     img:"/rabat.jpg",            flag:"👑"},
  {city:"Marrakech", img:"/MARRAKECH-CITY.webp", flag:"🌹"},
  {city:"Tanger",    img:"/Tanger.jpg",           flag:"🌊"},
  {city:"Agadir",    img:"/AGADIR.jpg",           flag:"🏖️"},
  {city:"Fès",       img:"/fes.webp",             flag:"🕌"},
];

export const BR = { red:"#E41C3A", green:"#00913F", blue:"#1A56DB", gold:"#F0B429", check:"#22C55E", purple:"#9333EA" };
export const PHASE_COLORS = {G:BR.red,"8":BR.purple,Q:BR.blue,S:BR.green,F:BR.gold};
export const TEAM_ACCENT = {
  Spain:"#AA151B",Argentina:"#74ACDF",France:"#002395",England:"#CF081F",
  Brazil:"#009C3B",Portugal:"#006600",Netherlands:"#FF6400",Morocco:"#E41C3A",
  Belgium:"#EF3340",Germany:"#000000",Croatia:"#FF0000",Senegal:"#00853F",
  Italy:"#009246",Colombia:"#FCD116",USA:"#002868",Mexico:"#006847",
  Uruguay:"#75AADB",Switzerland:"#FF0000",Japan:"#BC002D",Iran:"#239F40",
};
export const TEAM_DATA={
  "Morocco":     {flag:"🇲🇦",colors:["#C41E3A","#006233"],heroGradient:"linear-gradient(135deg,#C41E3A 0%,#006233 100%)",stars:["Hakim Ziyech","Achraf Hakimi","Brahim Diaz"]},
  "Spain":       {flag:"🇪🇸",colors:["#AA151B","#F1BF00"],heroGradient:"linear-gradient(135deg,#AA151B 0%,#F1BF00 100%)",stars:["Pedri","Lamine Yamal","Rodri"]},
  "Portugal":    {flag:"🇵🇹",colors:["#006600","#FF0000"],heroGradient:"linear-gradient(135deg,#006600 0%,#CC0000 100%)",stars:["Cristiano Ronaldo","Bernardo Silva","Rúben Dias"]},
  "France":      {flag:"🇫🇷",colors:["#002395","#ED2939"],heroGradient:"linear-gradient(135deg,#002395 0%,#ED2939 100%)",stars:["Kylian Mbappé","Antoine Griezmann","Aurélien Tchouaméni"]},
  "Argentina":   {flag:"🇦🇷",colors:["#75AADB","#002868"],heroGradient:"linear-gradient(135deg,#75AADB 0%,#002868 100%)",stars:["Lionel Messi","Julián Álvarez","Enzo Fernández"]},
  "Brazil":      {flag:"🇧🇷",colors:["#009C3B","#FFDF00"],heroGradient:"linear-gradient(135deg,#009C3B 0%,#FFDF00 100%)",stars:["Vinícius Jr","Rodrygo","Endrick"]},
  "Germany":     {flag:"🇩🇪",colors:["#DD0000","#1a1a1a"],heroGradient:"linear-gradient(135deg,#1a1a1a 0%,#DD0000 100%)",stars:["Jamal Musiala","Florian Wirtz","Kai Havertz"]},
  "England":     {flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿",colors:["#CF081F","#8B0000"],heroGradient:"linear-gradient(135deg,#CF081F 0%,#8B0000 100%)",stars:["Jude Bellingham","Phil Foden","Harry Kane"]},
  "Italy":       {flag:"🇮🇹",colors:["#003087","#009246"],heroGradient:"linear-gradient(135deg,#003087 0%,#009246 100%)",stars:["Gianluigi Donnarumma","Nicolo Barella","Federico Chiesa"]},
  "Netherlands": {flag:"🇳🇱",colors:["#FF6400","#C84B00"],heroGradient:"linear-gradient(135deg,#FF6400 0%,#C84B00 100%)",stars:["Cody Gakpo","Virgil van Dijk","Xavi Simons"]},
  "Belgium":     {flag:"🇧🇪",colors:["#EF3340","#1a1a1a"],heroGradient:"linear-gradient(135deg,#EF3340 0%,#1a1a1a 100%)",stars:["Kevin De Bruyne","Romelu Lukaku","Lois Openda"]},
  "Croatia":     {flag:"🇭🇷",colors:["#FF0000","#0093DD"],heroGradient:"linear-gradient(135deg,#FF0000 0%,#0093DD 100%)",stars:["Luka Modrić","Mateo Kovačić","Ivan Perišić"]},
  "USA":         {flag:"🇺🇸",colors:["#002868","#BF0A30"],heroGradient:"linear-gradient(135deg,#002868 0%,#BF0A30 100%)",stars:["Christian Pulisic","Tyler Adams","Gio Reyna"]},
  "Mexico":      {flag:"🇲🇽",colors:["#006847","#CE1126"],heroGradient:"linear-gradient(135deg,#006847 0%,#CE1126 100%)",stars:["Hirving Lozano","Edson Álvarez","Guillermo Ochoa"]},
  "Japan":       {flag:"🇯🇵",colors:["#BC002D","#8B0021"],heroGradient:"linear-gradient(135deg,#BC002D 0%,#8B0021 100%)",stars:["Kaoru Mitoma","Ritsu Doan","Takumi Minamino"]},
  "Senegal":     {flag:"🇸🇳",colors:["#00853F","#FDEF42"],heroGradient:"linear-gradient(135deg,#00853F 0%,#FDEF42 100%)",stars:["Sadio Mané","Kalidou Koulibaly","Idrissa Gueye"]},
  "Canada":      {flag:"🇨🇦",colors:["#CC0000","#8B0000"],heroGradient:"linear-gradient(135deg,#CC0000 0%,#8B0000 100%)",stars:["Alphonso Davies","Jonathan David","Cyle Larin"]},
  "Australia":   {flag:"🇦🇺",colors:["#00008B","#FFD700"],heroGradient:"linear-gradient(135deg,#00008B 0%,#FFD700 100%)",stars:["Mathew Ryan","Martin Boyle","Riley McGree"]},
  "South Korea": {flag:"🇰🇷",colors:["#CD2E3A","#003478"],heroGradient:"linear-gradient(135deg,#CD2E3A 0%,#003478 100%)",stars:["Son Heung-min","Lee Kang-in","Kim Min-jae"]},
  "Saudi Arabia":{flag:"🇸🇦",colors:["#006C35","#004A25"],heroGradient:"linear-gradient(135deg,#006C35 0%,#004A25 100%)",stars:["Salem Al-Dawsari","Mohammed Al-Owais","Firas Al-Buraikan"]},
  "Qatar":       {flag:"🇶🇦",colors:["#8D1B3D","#5C1128"],heroGradient:"linear-gradient(135deg,#8D1B3D 0%,#5C1128 100%)",stars:["Akram Afif","Almoez Ali","Hassan Al-Haydos"]},
  "Tunisia":     {flag:"🇹🇳",colors:["#E70013","#A80010"],heroGradient:"linear-gradient(135deg,#E70013 0%,#A80010 100%)",stars:["Wahbi Khazri","Youssef Msakni","Ellyes Skhiri"]},
  "Cameroon":    {flag:"🇨🇲",colors:["#007A5E","#CE1126"],heroGradient:"linear-gradient(135deg,#007A5E 0%,#CE1126 100%)",stars:["André Onana","Bryan Mbeumo","Karl Toko Ekambi"]},
  "Ghana":       {flag:"🇬🇭",colors:["#006B3F","#FCD116"],heroGradient:"linear-gradient(135deg,#006B3F 0%,#FCD116 100%)",stars:["Mohammed Kudus","Thomas Partey","Jordan Ayew"]},
  "Nigeria":     {flag:"🇳🇬",colors:["#008751","#005F38"],heroGradient:"linear-gradient(135deg,#008751 0%,#005F38 100%)",stars:["Victor Osimhen","Wilfred Ndidi","Kelechi Iheanacho"]},
  "Ecuador":     {flag:"🇪🇨",colors:["#FFD100","#003087"],heroGradient:"linear-gradient(135deg,#003087 0%,#FFD100 100%)",stars:["Moisés Caicedo","Enner Valencia","Pervis Estupiñán"]},
  "Uruguay":     {flag:"🇺🇾",colors:["#75AADB","#4A7FA8"],heroGradient:"linear-gradient(135deg,#75AADB 0%,#4A7FA8 100%)",stars:["Federico Valverde","Darwin Núñez","Ronald Araújo"]},
  "Colombia":    {flag:"🇨🇴",colors:["#FCD116","#003087"],heroGradient:"linear-gradient(135deg,#003087 0%,#FCD116 100%)",stars:["James Rodríguez","Luis Díaz","Richard Rios"]},
  "Chile":       {flag:"🇨🇱",colors:["#D52B1E","#003087"],heroGradient:"linear-gradient(135deg,#D52B1E 0%,#003087 100%)",stars:["Alexis Sánchez","Arturo Vidal","Charles Aránguiz"]},
  "Peru":        {flag:"🇵🇪",colors:["#D91023","#A00B1A"],heroGradient:"linear-gradient(135deg,#D91023 0%,#A00B1A 100%)",stars:["Paolo Guerrero","André Carrillo","Gianluca Lapadula"]},
  "Serbia":      {flag:"🇷🇸",colors:["#C6363C","#0C4076"],heroGradient:"linear-gradient(135deg,#C6363C 0%,#0C4076 100%)",stars:["Dušan Vlahović","Aleksandar Mitrović","Sergej Milinković-Savić"]},
  "Switzerland": {flag:"🇨🇭",colors:["#FF0000","#CC0000"],heroGradient:"linear-gradient(135deg,#FF0000 0%,#CC0000 100%)",stars:["Granit Xhaka","Xherdan Shaqiri","Yann Sommer"]},
  "Denmark":     {flag:"🇩🇰",colors:["#C8102E","#9A0C24"],heroGradient:"linear-gradient(135deg,#C8102E 0%,#9A0C24 100%)",stars:["Christian Eriksen","Pierre-Emile Højbjerg","Rasmus Højlund"]},
  "Sweden":      {flag:"🇸🇪",colors:["#006AA7","#FECC02"],heroGradient:"linear-gradient(135deg,#006AA7 0%,#FECC02 100%)",stars:["Alexander Isak","Viktor Gyökeres","Dejan Kulusevski"]},
  "Poland":      {flag:"🇵🇱",colors:["#DC143C","#A00F2D"],heroGradient:"linear-gradient(135deg,#DC143C 0%,#A00F2D 100%)",stars:["Robert Lewandowski","Piotr Zieliński","Wojciech Szczęsny"]},
  "Austria":     {flag:"🇦🇹",colors:["#ED2939","#B51D29"],heroGradient:"linear-gradient(135deg,#ED2939 0%,#B51D29 100%)",stars:["Marcel Sabitzer","David Alaba","Marko Arnautović"]},
  "Czechia":     {flag:"🇨🇿",colors:["#D7141A","#11457E"],heroGradient:"linear-gradient(135deg,#D7141A 0%,#11457E 100%)",stars:["Tomáš Souček","Patrik Schick","Vladimír Coufal"]},
  "Turkey":      {flag:"🇹🇷",colors:["#E30A17","#AA0811"],heroGradient:"linear-gradient(135deg,#E30A17 0%,#AA0811 100%)",stars:["Hakan Çalhanoğlu","Arda Güler","Kerem Aktürkoğlu"]},
  "Iran":        {flag:"🇮🇷",colors:["#239F40","#DA0000"],heroGradient:"linear-gradient(135deg,#239F40 0%,#DA0000 100%)",stars:["Mehdi Taremi","Sardar Azmoun","Alireza Jahanbakhsh"]},
  "Egypt":       {flag:"🇪🇬",colors:["#CE1126","#9A0C1C"],heroGradient:"linear-gradient(135deg,#CE1126 0%,#9A0C1C 100%)",stars:["Mohamed Salah","Ahmed Hegazi","Mostafa Mohamed"]},
  "Algeria":     {flag:"🇩🇿",colors:["#006233","#004A26"],heroGradient:"linear-gradient(135deg,#006233 0%,#004A26 100%)",stars:["Riyad Mahrez","Islam Slimani","Said Benrahma"]},
  "Ivory Coast": {flag:"🇨🇮",colors:["#F77F00","#009A44"],heroGradient:"linear-gradient(135deg,#F77F00 0%,#009A44 100%)",stars:["Sébastien Haller","Franck Kessié","Wilfried Zaha"]},
  "South Africa":{flag:"🇿🇦",colors:["#007A4D","#FFB81C"],heroGradient:"linear-gradient(135deg,#007A4D 0%,#FFB81C 100%)",stars:["Percy Tau","Lebo Mothiba","Ronwen Williams"]},
  "Costa Rica":  {flag:"🇨🇷",colors:["#002B7F","#CF142B"],heroGradient:"linear-gradient(135deg,#002B7F 0%,#CF142B 100%)",stars:["Keylor Navas","Joel Campbell","Anthony Contreras"]},
  "Panama":      {flag:"🇵🇦",colors:["#002B7F","#CE1126"],heroGradient:"linear-gradient(135deg,#002B7F 0%,#CE1126 100%)",stars:["Roderick Miller","Anibal Godoy","Rolando Blackburn"]},
  "Jamaica":     {flag:"🇯🇲",colors:["#FED100","#1a1a1a"],heroGradient:"linear-gradient(135deg,#1a1a1a 0%,#FED100 100%)",stars:["Leon Bailey","Michail Antonio","Bobby Decordova-Reid"]},
  "Scotland":    {flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿",colors:["#003F87","#002A5E"],heroGradient:"linear-gradient(135deg,#003F87 0%,#002A5E 100%)",stars:["Andrew Robertson","Scott McTominay","John McGinn"]},
  "Wales":       {flag:"🏴󠁧󠁢󠁷󠁬󠁳󠁿",colors:["#C8102E","#00A499"],heroGradient:"linear-gradient(135deg,#C8102E 0%,#00A499 100%)",stars:["Brennan Johnson","Neco Williams","Harry Wilson"]},
};
export const PLAYERS_IMG={
  MA:"/players-ma.webp",
  BR:"/players-br.webp",
  DE:"/players-de.webp",
  AR:"/players-ar.webp",
  FR:"/players-fr.webp",
  EN:"/players-en.webp",
  PT:"/players-pt.webp",
  ES:"/players-es.webp",
  NL:"/players-nl.png",
  BE:"/players-be.png",
  HR:"/players-hr.png",
  US:"/players-us.png",
  MX:"/players-mx.png",
  JP:"/players-jp.png",
  SN:"/players-sn.png",
  CA:"/players-ca.png",
  AU:"/players-au.png",
  KR:"/players-kr.png",
  SA:"/players-sa.png",
  QA:"/players-qa.png",
  TN:"/players-tn.png",
  GH:"/players-gh.png",
  EC:"/players-ec.png",
  UY:"/players-uy.png",
  CO:"/players-co.png",
  IT:"/players-it.png",
  default:"/players-default.webp",
};
export const TEAM_ISO={
  "Morocco":"ma","Spain":"es","Portugal":"pt","France":"fr","Argentina":"ar",
  "Brazil":"br","Germany":"de","England":"gb-eng","Italy":"it","Netherlands":"nl",
  "Belgium":"be","Croatia":"hr","USA":"us","Mexico":"mx","Japan":"jp",
  "Senegal":"sn","Canada":"ca","Australia":"au","South Korea":"kr",
  "Saudi Arabia":"sa","Qatar":"qa","Tunisia":"tn","Cameroon":"cm","Ghana":"gh",
  "Nigeria":"ng","Ecuador":"ec","Uruguay":"uy","Colombia":"co","Chile":"cl",
  "Peru":"pe","Serbia":"rs","Switzerland":"ch","Denmark":"dk","Sweden":"se",
  "Poland":"pl","Austria":"at","Czechia":"cz","Turkey":"tr","Iran":"ir",
  "Egypt":"eg","Algeria":"dz","Ivory Coast":"ci","South Africa":"za",
  "Costa Rica":"cr","Panama":"pa","Jamaica":"jm","Scotland":"gb-sct","Wales":"gb-wls",
};
export const TEAM_GROUPS={
  "Morocco":"C","Brazil":"C","Scotland":"C","Haiti":"C",
  "France":"I","Senegal":"I","Iraq":"I","Norway":"I",
  "Spain":"H","Saudi Arabia":"H","Uruguay":"H","South Korea":"H",
  "Argentina":"J","Algeria":"J","Austria":"J","Jordan":"J",
  "Germany":"E","Japan":"E","Ecuador":"E","Czechia":"E",
  "England":"L","Croatia":"L","Ghana":"L","Panama":"L",
  "Portugal":"K","Colombia":"K","DR Congo":"K","Uzbekistan":"K",
  "Netherlands":"F","Tunisia":"F","New Zealand":"F",
  "Italy":"G","Ivory Coast":"G","Belgium":"G","Paraguay":"G",
  "USA":"D","Australia":"D","Iran":"D","Curacao":"D",
  "Canada":"B","Qatar":"B","Switzerland":"B","Bosnia and Herzegovina":"B",
  "Mexico":"A","South Africa":"A",
};

export const TEAM_OPPONENTS={
  Morocco:'Brésil · Écosse · Haïti',
  Brazil:'Maroc · Écosse · Haïti',
  Scotland:'Brésil · Maroc · Haïti',
  Haiti:'Brésil · Maroc · Écosse',
  France:'Sénégal · Irak · Norvège',
  Senegal:'France · Irak · Norvège',
  Iraq:'France · Sénégal · Norvège',
  Norway:'France · Sénégal · Irak',
  Spain:'Cap-Vert · Arabie Saoudite · Uruguay',
  Argentina:'Algérie · Autriche · Jordanie',
  Algeria:'Argentine · Autriche · Jordanie',
  Austria:'Argentine · Algérie · Jordanie',
  Jordan:'Argentine · Algérie · Autriche',
  Germany:'Japon · Équateur · Curaçao',
  Japan:'Allemagne · Équateur · Curaçao',
  Ecuador:'Allemagne · Japon · Curaçao',
  England:'Croatie · Ghana · Panama',
  Croatia:'Angleterre · Ghana · Panama',
  Ghana:'Angleterre · Croatie · Panama',
  Portugal:'Colombie · RD Congo · Ouzbékistan',
  Colombia:'Portugal · RD Congo · Ouzbékistan',
  Netherlands:'Belgique · Tunisie · Nouvelle-Zélande',
  Tunisia:'Pays-Bas · Belgique · Nouvelle-Zélande',
  Belgium:'Pays-Bas · Italie · Côte d\'Ivoire',
  Italy:'Belgique · Pays-Bas · Côte d\'Ivoire',
  USA:'Australie · Iran · Curaçao',
  Australia:'USA · Iran · Curaçao',
  Mexico:'Corée · Afrique du Sud · Czechia',
  Canada:'Qatar · Suisse · Bosnie',
  Uruguay:'Espagne · Cap-Vert · Arabie Saoudite',
  'Saudi Arabia':'Espagne · Uruguay · Cap-Vert',
  'South Korea':'Mexique · Afrique du Sud · Czechia',
};

export const WELCOME_FAN={
  fr:(f,n)=>`Bienvenue supporter de ${n} !`,
  en:(f,n)=>`Welcome ${n} fan!`,
  ar:(f,n)=>`أهلاً مشجع ${n}!`,
  es:(f,n)=>`¡Bienvenido hincha de ${n}!`,
  pt:(f,n)=>`Bem-vindo torcedor de ${n}!`,
  zh:(f,n)=>`欢迎 ${n} 球迷！`,
};

// Position + number overrides for featured teams
export const PLAYER_DETAILS_OVERRIDE={
  "Morocco":     [{pos:"DEF",number:7},{pos:"FWD",number:2},{pos:"MID",number:10}],
  "Spain":       [{pos:"MID",number:8},{pos:"FWD",number:19},{pos:"MID",number:16}],
  "France":      [{pos:"FWD",number:10},{pos:"FWD",number:7},{pos:"MID",number:8}],
  "Argentina":   [{pos:"FWD",number:10},{pos:"FWD",number:9},{pos:"MID",number:24}],
  "Brazil":      [{pos:"FWD",number:7},{pos:"FWD",number:11},{pos:"FWD",number:9}],
  "England":     [{pos:"MID",number:5},{pos:"FWD",number:7},{pos:"MID",number:4}],
  "Germany":     [{pos:"MID",number:10},{pos:"MID",number:10},{pos:"FWD",number:7}],
  "Portugal":    [{pos:"FWD",number:7},{pos:"MID",number:8},{pos:"MID",number:10}],
  "Netherlands": [{pos:"FWD",number:11},{pos:"DEF",number:4},{pos:"MID",number:21}],
  "Italy":       [{pos:"GK",number:1},{pos:"MID",number:8},{pos:"FWD",number:14}],
  "Belgium":     [{pos:"MID",number:7},{pos:"FWD",number:9},{pos:"FWD",number:11}],
  "Croatia":     [{pos:"MID",number:10},{pos:"DEF",number:24},{pos:"MID",number:8}],
  "USA":         [{pos:"MID",number:10},{pos:"MID",number:8},{pos:"MID",number:7}],
  "Japan":       [{pos:"FWD",number:9},{pos:"FWD",number:10},{pos:"MID",number:8}],
  "Senegal":     [{pos:"FWD",number:10},{pos:"DEF",number:3},{pos:"FWD",number:23}],
};
export const TEAM_PLAYERS=Object.fromEntries(
  Object.entries(TEAM_DATA).map(([team,data])=>{
    const bg=data.colors[0].replace("#","");
    const details=PLAYER_DETAILS_OVERRIDE[team]||[{pos:"FWD",number:10},{pos:"MID",number:7},{pos:"DEF",number:4}];
    return[team,data.stars.map((name,i)=>({
      name,
      pos:details[i]?.pos||"MID",
      number:details[i]?.number||10,
      img:`https://ui-avatars.com/api/?name=${name.replace(/ /g,"+")}&size=200&background=${bg}&color=fff&bold=true`,
    }))];
  })
);

export const PLAYERS={
  MA:{p1:"Achraf Hakimi",        n1:2,  p2:"Yassine Bounou",     n2:1,  p3:"Sofyan Amrabat",       n3:8},
  BR:{p1:"Vinícius Jr",          n1:7,  p2:"Endrick",             n2:9,  p3:"Rodrygo",              n3:11},
  DE:{p1:"Jamal Musiala",        n1:10, p2:"Florian Wirtz",       n2:25, p3:"Joshua Kimmich",       n3:6},
  AR:{p1:"Lionel Messi",         n1:10, p2:"Julián Álvarez",      n2:9,  p3:"Rodrigo De Paul",      n3:7},
  FR:{p1:"Kylian Mbappé",        n1:10, p2:"Ousmane Dembélé",     n2:11, p3:"Eduardo Camavinga",    n3:8},
  EN:{p1:"Jude Bellingham",      n1:10, p2:"Harry Kane",           n2:9,  p3:"Bukayo Saka",          n3:7},
  PT:{p1:"Cristiano Ronaldo",    n1:7,  p2:"Bruno Fernandes",      n2:8,  p3:"João Félix",           n3:11},
  ES:{p1:"Lamine Yamal",         n1:19, p2:"Álvaro Morata",        n2:7,  p3:"Pedri",                n3:8},
  NL:{p1:"Virgil van Dijk",      n1:4,  p2:"Memphis Depay",        n2:10, p3:"Cody Gakpo",           n3:11},
  BE:{p1:"Kevin De Bruyne",      n1:7,  p2:"Romelu Lukaku",        n2:9,  p3:"Youri Tielemans",      n3:8},
  HR:{p1:"Luka Modrić",          n1:10, p2:"Mateo Kovačić",        n2:8,  p3:"Ivan Perišić",         n3:4},
  US:{p1:"Christian Pulisic",    n1:10, p2:"Gio Reyna",             n2:7,  p3:"Weston McKennie",      n3:8},
  MX:{p1:"Hirving Lozano",       n1:22, p2:"Edson Álvarez",         n2:14, p3:"Roberto Alvarado",     n3:17},
  JP:{p1:"Kaoru Mitoma",         n1:10, p2:"Ritsu Doan",            n2:8,  p3:"Daichi Kamada",        n3:14},
  SN:{p1:"Ismaïla Sarr",         n1:7,  p2:"Lamine Camara",         n2:10, p3:"Nicolas Jackson",      n3:9},
  CA:{p1:"Alphonso Davies",      n1:19, p2:"Jonathan David",        n2:9,  p3:"Tajon Buchanan",       n3:3},
  AU:{p1:"Mathew Leckie",        n1:7,  p2:"Mitchell Duke",         n2:9,  p3:"Aaron Mooy",           n3:13},
  KR:{p1:"Son Heung-min",        n1:7,  p2:"Lee Kang-in",           n2:10, p3:"Hwang Hee-chan",       n3:9},
  SA:{p1:"Salem Al-Dawsari",     n1:10, p2:"Firas Al-Buraikan",     n2:9,  p3:"Saleh Al-Shehri",      n3:7},
  QA:{p1:"Akram Afif",           n1:11, p2:"Hassan Al-Haydos",      n2:10, p3:"Almoez Ali",           n3:9},
  TN:{p1:"Youssef Msakni",       n1:10, p2:"Sayfallah Ltaief",      n2:9,  p3:"Hannibal Mejbri",      n3:8},
  GH:{p1:"Mohammed Kudus",       n1:10, p2:"Jordan Ayew",            n2:9,  p3:"Thomas Partey",        n3:5},
  EC:{p1:"Enner Valencia",       n1:13, p2:"Moisés Caicedo",         n2:10, p3:"Piero Hincapié",      n3:3},
  UY:{p1:"Federico Valverde",    n1:8,  p2:"Darwin Núñez",           n2:11, p3:"Ronald Araújo",        n3:4},
  CO:{p1:"James Rodríguez",      n1:10, p2:"Luis Díaz",              n2:7,  p3:"Richard Ríos",         n3:8},
  IT:{p1:"Gianluigi Donnarumma", n1:1,  p2:"Sandro Tonali",          n2:8,  p3:"Giacomo Raspadori",    n3:18},
};

export const POI_CATS=[
  {id:"hotel",     icon:"🏨",color:"#1A56DB",label:"Hotels"},
  {id:"pharmacy",  icon:"💊",color:"#00823C",label:"Pharmacies"},
  {id:"restaurant",icon:"🍽️",color:"#F5A623",label:"Restaurants"},
  {id:"hospital",  icon:"🏥",color:"#C41E3A",label:"Hospitals"},
  {id:"mosque",    icon:"🕌",color:"#0D9488",label:"Mosquées"},
  {id:"police",    icon:"🚔",color:"#1E3A5F",label:"Police"},
  {id:"transport", icon:"🚇",color:"#7C3AED",label:"Transport"},
  {id:"monument",  icon:"🏛️",color:"#D97706",label:"Monuments"},
  {id:"beach",     icon:"🏖️",color:"#06B6D4",label:"Plages"},
  {id:"market",    icon:"🛍️",color:"#EC4899",label:"Marchés"},
];
export const POIS=[
  // ── CASABLANCA ──
  {id:"casa_hotel_1", name:"Kenzi Tower Hotel",                  category:"hotel",      city:"Casablanca", lat:33.5882,lng:-7.6322, rating:4.5,price:"$$$",phone:"+212 522 97 80 00",address:"Bd Zerktouni, Casablanca",           hours:"24/7"},
  {id:"casa_hotel_2", name:"Hyatt Regency Casablanca",           category:"hotel",      city:"Casablanca", lat:33.6014,lng:-7.6322, rating:4.7,price:"$$$",phone:"+212 522 12 34 00",address:"Pl. des Nations Unies, Casablanca",  hours:"24/7"},
  {id:"casa_hotel_3", name:"Hôtel Barceló Casablanca",           category:"hotel",      city:"Casablanca", lat:33.5950,lng:-7.6195, rating:4.3,price:"$$", phone:"+212 522 48 18 00",address:"Bd d'Anfa, Casablanca",             hours:"24/7"},
  {id:"casa_hotel_4", name:"Pestana CR7 Casablanca",             category:"hotel",      city:"Casablanca", lat:33.5989,lng:-7.6138, rating:4.4,price:"$$", phone:"+212 522 22 60 00",address:"Bd de la Corniche, Casablanca",     hours:"24/7"},
  {id:"casa_hotel_5", name:"Riad Jnane Sherazade",               category:"hotel",      city:"Casablanca", lat:33.5731,lng:-7.5898, rating:4.2,price:"$$", phone:"+212 522 30 10 00",address:"Ancienne Médina, Casablanca",       hours:"24/7"},
  {id:"casa_pharm_1", name:"Pharmacie Maarif",                   category:"pharmacy",   city:"Casablanca", lat:33.5804,lng:-7.6329, phone:"+212 522 25 40 00",address:"Rue Abou Abdellah, Maarif",          hours:"8:00-22:00"},
  {id:"casa_pharm_2", name:"Pharmacie Ain Diab",                 category:"pharmacy",   city:"Casablanca", lat:33.5934,lng:-7.6656, phone:"+212 522 79 12 00",address:"Bd de la Corniche, Ain Diab",        hours:"8:00-22:00"},
  {id:"casa_pharm_3", name:"Pharmacie de Garde CIL",             category:"pharmacy",   city:"Casablanca", lat:33.5720,lng:-7.5890, phone:"+212 522 26 00 00",address:"Ancienne Médina, Casablanca",        hours:"24/7"},
  {id:"casa_rest_1",  name:"Rick's Café",                        category:"restaurant", city:"Casablanca", lat:33.6028,lng:-7.6149, rating:4.6,price:"$$$",phone:"+212 522 27 42 07",address:"248 Bd Sour Jdid, Casablanca",      hours:"12:00-23:00"},
  {id:"casa_rest_2",  name:"La Sqala",                           category:"restaurant", city:"Casablanca", lat:33.6042,lng:-7.6180, rating:4.4,price:"$$", phone:"+212 522 26 09 60",address:"Bd des Almohades, Casablanca",      hours:"11:00-23:00"},
  {id:"casa_rest_3",  name:"Blend Gourmet Burger",               category:"restaurant", city:"Casablanca", lat:33.5886,lng:-7.6372, rating:4.5,price:"$$", phone:"+212 522 98 00 00",address:"Quartier Maarif, Casablanca",       hours:"12:00-23:00"},
  {id:"casa_rest_4",  name:"Basmane",                            category:"restaurant", city:"Casablanca", lat:33.5933,lng:-7.6256, rating:4.3,price:"$$", phone:"+212 522 36 10 00",address:"Bd Mohammed V, Casablanca",         hours:"12:00-22:00"},
  {id:"casa_hosp_1",  name:"CHU Ibn Rochd",                      category:"hospital",   city:"Casablanca", lat:33.5824,lng:-7.5906, phone:"+212 522 22 41 41",address:"1 Rue des Hôpitaux, Casablanca",     hours:"24/7"},
  {id:"casa_hosp_2",  name:"Clinique Ghandi",                    category:"hospital",   city:"Casablanca", lat:33.5878,lng:-7.6289, phone:"+212 522 25 15 15",address:"Bd Ghandi, Casablanca",              hours:"24/7"},
  {id:"casa_trans_1", name:"Gare Casa Voyageurs",                category:"transport",  city:"Casablanca", lat:33.5895,lng:-7.5898, phone:"+212 522 22 30 11",address:"Bd Mohammed V, Casablanca",          hours:"5:00-23:00"},
  {id:"casa_trans_2", name:"Station Tramway Casa",               category:"transport",  city:"Casablanca", lat:33.5900,lng:-7.6100, address:"Bd Mohammed V, Casablanca",          hours:"6:00-23:00"},
  // ── RABAT ──
  {id:"rabat_hotel_1",name:"Sofitel Rabat Jardin des Roses",      category:"hotel",      city:"Rabat",      lat:33.9716,lng:-6.8498, rating:4.8,price:"$$$",phone:"+212 537 67 56 56",address:"Rue Jabel Al Anayat, Rabat",         hours:"24/7"},
  {id:"rabat_hotel_2",name:"Tour Hassan Palace",                  category:"hotel",      city:"Rabat",      lat:33.9631,lng:-6.8293, rating:4.6,price:"$$$",phone:"+212 537 23 90 00",address:"26 Rue Chellah, Rabat",              hours:"24/7"},
  {id:"rabat_hotel_3",name:"Riad Dar Al Batoul",                  category:"hotel",      city:"Rabat",      lat:34.0256,lng:-6.8361, rating:4.4,price:"$$", phone:"+212 537 70 28 00",address:"Médina de Rabat",                    hours:"24/7"},
  {id:"rabat_pharm_1",name:"Pharmacie Agdal",                     category:"pharmacy",   city:"Rabat",      lat:33.9898,lng:-6.8624, phone:"+212 537 67 20 00",address:"Av. Fal Ould Oumeir, Agdal, Rabat",  hours:"8:00-21:00"},
  {id:"rabat_pharm_2",name:"Pharmacie Hay Riad",                  category:"pharmacy",   city:"Rabat",      lat:33.9572,lng:-6.8759, phone:"+212 537 71 40 00",address:"Hay Riad, Rabat",                    hours:"8:00-21:00"},
  {id:"rabat_rest_1", name:"Le Dhow",                             category:"restaurant", city:"Rabat",      lat:34.0207,lng:-6.8359, rating:4.5,price:"$$$",phone:"+212 537 70 19 00",address:"Bou Regreg, Rabat",                  hours:"12:00-23:00"},
  {id:"rabat_rest_2", name:"Dar Zaki",                            category:"restaurant", city:"Rabat",      lat:34.0234,lng:-6.8334, rating:4.4,price:"$$", phone:"+212 537 70 22 00",address:"6 Rue Souika, Médina Rabat",         hours:"12:00-22:00"},
  {id:"rabat_rest_3", name:"Cosmopolitan Rabat",                  category:"restaurant", city:"Rabat",      lat:33.9894,lng:-6.8502, rating:4.3,price:"$$", phone:"+212 537 67 45 00",address:"Agdal, Rabat",                       hours:"12:00-23:00"},
  {id:"rabat_hosp_1", name:"CHU Rabat Avicenne",                  category:"hospital",   city:"Rabat",      lat:33.9669,lng:-6.8416, phone:"+212 537 67 44 44",address:"Av. Ibn Sina, Rabat",                hours:"24/7"},
  {id:"rabat_hosp_2", name:"Hôpital Cheikh Zaïd",                category:"hospital",   city:"Rabat",      lat:33.9508,lng:-6.8826, phone:"+212 537 56 60 00",address:"Hay Riad, Rabat",                    hours:"24/7"},
  // ── MARRAKECH ──
  {id:"mkch_hotel_1", name:"Royal Mansour Marrakech",             category:"hotel",      city:"Marrakech",  lat:31.6242,lng:-7.9884, rating:5.0,price:"$$$",phone:"+212 529 80 80 80",address:"Rue Abou Abbas El Sebti, Marrakech", hours:"24/7"},
  {id:"mkch_hotel_2", name:"La Mamounia",                         category:"hotel",      city:"Marrakech",  lat:31.6204,lng:-7.9985, rating:4.9,price:"$$$",phone:"+212 524 38 86 00",address:"Av. Bab Jdid, Marrakech",            hours:"24/7"},
  {id:"mkch_hotel_3", name:"Riad Kniza",                          category:"hotel",      city:"Marrakech",  lat:31.6290,lng:-7.9850, rating:4.7,price:"$$", phone:"+212 524 37 69 42",address:"34 Derb l'Hôtel, Médina Marrakech",  hours:"24/7"},
  {id:"mkch_pharm_1", name:"Pharmacie Place Jemaa",               category:"pharmacy",   city:"Marrakech",  lat:31.6257,lng:-7.9890, phone:"+212 524 44 18 00",address:"Pl. Jemaa el-Fna, Marrakech",        hours:"8:00-22:00"},
  {id:"mkch_pharm_2", name:"Pharmacie Guéliz",                    category:"pharmacy",   city:"Marrakech",  lat:31.6357,lng:-8.0104, phone:"+212 524 43 20 00",address:"Bd Mohammed Zerktouni, Guéliz",      hours:"8:00-21:00"},
  {id:"mkch_rest_1",  name:"Nomad Marrakech",                     category:"restaurant", city:"Marrakech",  lat:31.6312,lng:-7.9862, rating:4.6,price:"$$", phone:"+212 524 38 16 09",address:"1 Derb Aagnaou, Médina",             hours:"8:00-23:00"},
  {id:"mkch_rest_2",  name:"Café Clock Marrakech",                category:"restaurant", city:"Marrakech",  lat:31.6290,lng:-7.9832, rating:4.4,price:"$",  phone:"+212 524 37 83 67",address:"224 Derb Chtouka, Kasbah",           hours:"9:00-22:00"},
  {id:"mkch_rest_3",  name:"Le Jardin Marrakech",                 category:"restaurant", city:"Marrakech",  lat:31.6302,lng:-7.9860, rating:4.5,price:"$$", phone:"+212 524 37 82 95",address:"32 Souk Sidi Abdelaziz, Médina",     hours:"10:00-23:00"},
  {id:"mkch_hosp_1",  name:"CHU Mohammed VI Marrakech",           category:"hospital",   city:"Marrakech",  lat:31.6504,lng:-8.0018, phone:"+212 524 30 91 00",address:"Quartier Amerchich, Marrakech",      hours:"24/7"},
  {id:"mkch_hosp_2",  name:"Clinique Internationale Marrakech",   category:"hospital",   city:"Marrakech",  lat:31.6380,lng:-8.0090, phone:"+212 524 44 79 99",address:"Bd Mohammed VI, Marrakech",          hours:"24/7"},
  // ── TANGER ──
  {id:"tng_hotel_1",  name:"Hilton Tanger City Centre",           category:"hotel",      city:"Tanger",     lat:35.7671,lng:-5.8013, rating:4.5,price:"$$$",phone:"+212 539 39 39 00",address:"Pl. du Maghreb Arabe, Tanger",       hours:"24/7"},
  {id:"tng_hotel_2",  name:"El Minzah Hotel",                     category:"hotel",      city:"Tanger",     lat:35.7850,lng:-5.8110, rating:4.6,price:"$$$",phone:"+212 539 33 58 85",address:"85 Rue de la Liberté, Tanger",       hours:"24/7"},
  {id:"tng_hotel_3",  name:"Fairmont Tazia Tanger",               category:"hotel",      city:"Tanger",     lat:35.7550,lng:-5.8250, rating:4.8,price:"$$$",phone:"+212 539 31 00 00",address:"Av. de Madrid, Tanger",              hours:"24/7"},
  {id:"tng_pharm_1",  name:"Pharmacie Pasteur",                   category:"pharmacy",   city:"Tanger",     lat:35.7793,lng:-5.8132, phone:"+212 539 93 12 00",address:"Bd Pasteur, Tanger",                 hours:"8:00-22:00"},
  {id:"tng_pharm_2",  name:"Pharmacie Iberia",                    category:"pharmacy",   city:"Tanger",     lat:35.7835,lng:-5.8090, phone:"+212 539 94 20 00",address:"Av. d'Espagne, Tanger",              hours:"8:00-21:00"},
  {id:"tng_rest_1",   name:"El Morocco Club",                     category:"restaurant", city:"Tanger",     lat:35.7870,lng:-5.8130, rating:4.7,price:"$$$",phone:"+212 539 94 81 39",address:"Pl. du Grand Socco, Tanger",         hours:"12:00-23:00"},
  {id:"tng_rest_2",   name:"Salon Bleu Tanger",                   category:"restaurant", city:"Tanger",     lat:35.7868,lng:-5.8105, rating:4.6,price:"$$", phone:"+212 539 37 22 15",address:"Médina, Tanger",                     hours:"11:00-23:00"},
  {id:"tng_hosp_1",   name:"Hôpital Mohammed V Tanger",           category:"hospital",   city:"Tanger",     lat:35.7631,lng:-5.8200, phone:"+212 539 32 30 00",address:"Av. des FAR, Tanger",                hours:"24/7"},
  // ── AGADIR ──
  {id:"agd_hotel_1",  name:"Sofitel Agadir Thalassa Sea & Spa",   category:"hotel",      city:"Agadir",     lat:30.4278,lng:-9.5981, rating:4.7,price:"$$$",phone:"+212 528 82 00 00",address:"Baie des Palmiers, Agadir",          hours:"24/7"},
  {id:"agd_hotel_2",  name:"Tikida Beach Hotel",                  category:"hotel",      city:"Agadir",     lat:30.4200,lng:-9.6025, rating:4.5,price:"$$", phone:"+212 528 84 54 00",address:"Chemin des Dunes, Agadir",           hours:"24/7"},
  {id:"agd_hotel_3",  name:"Iberostar Founty Beach",              category:"hotel",      city:"Agadir",     lat:30.4150,lng:-9.6050, rating:4.4,price:"$$", phone:"+212 528 28 00 00",address:"Baie des Palmiers, Agadir",          hours:"24/7"},
  {id:"agd_pharm_1",  name:"Pharmacie Talborjt",                  category:"pharmacy",   city:"Agadir",     lat:30.4260,lng:-9.5980, phone:"+212 528 82 10 00",address:"Av. Prince Moulay Abdellah, Agadir",  hours:"8:00-21:00"},
  {id:"agd_pharm_2",  name:"Pharmacie Hassan II Agadir",          category:"pharmacy",   city:"Agadir",     lat:30.4300,lng:-9.5900, phone:"+212 528 84 60 00",address:"Av. Hassan II, Agadir",              hours:"8:00-22:00"},
  {id:"agd_rest_1",   name:"Pure Passion Restaurant",             category:"restaurant", city:"Agadir",     lat:30.4233,lng:-9.5988, rating:4.5,price:"$$", phone:"+212 528 84 11 00",address:"Cité Founty, Agadir",                hours:"12:00-23:00"},
  {id:"agd_rest_2",   name:"Le Jardin d'Eau",                     category:"restaurant", city:"Agadir",     lat:30.4280,lng:-9.6020, rating:4.4,price:"$$", phone:"+212 528 82 20 00",address:"Baie des Palmiers, Agadir",          hours:"12:00-22:00"},
  {id:"agd_hosp_1",   name:"Hôpital Hassan II Agadir",            category:"hospital",   city:"Agadir",     lat:30.4200,lng:-9.5850, phone:"+212 528 82 11 11",address:"Av. Hassan II, Agadir",              hours:"24/7"},
  // ── FÈS ──
  {id:"fes_hotel_1",  name:"Riad Fès",                            category:"hotel",      city:"Fès",        lat:34.0614,lng:-4.9786, rating:4.7,price:"$$$",phone:"+212 535 94 76 10",address:"5 Derb Ben Slimane, Médina Fès",     hours:"24/7"},
  {id:"fes_hotel_2",  name:"Palais Faraj Suites & Spa",           category:"hotel",      city:"Fès",        lat:34.0650,lng:-4.9770, rating:4.6,price:"$$$",phone:"+212 535 63 53 56",address:"Quartier Ziat, Fès El Bali",         hours:"24/7"},
  {id:"fes_hotel_3",  name:"Hotel Sahrai",                        category:"hotel",      city:"Fès",        lat:34.0480,lng:-4.9920, rating:4.5,price:"$$", phone:"+212 535 94 03 32",address:"Dhar El Mehraz, Fès",                hours:"24/7"},
  {id:"fes_pharm_1",  name:"Pharmacie Bab Boujloud",              category:"pharmacy",   city:"Fès",        lat:34.0640,lng:-4.9810, phone:"+212 535 63 50 00",address:"Bab Boujloud, Médina Fès",           hours:"8:00-22:00"},
  {id:"fes_pharm_2",  name:"Pharmacie Ville Nouvelle Fès",        category:"pharmacy",   city:"Fès",        lat:34.0340,lng:-4.9998, phone:"+212 535 65 20 00",address:"Bd Mohammed V, Fès",                 hours:"8:00-21:00"},
  {id:"fes_rest_1",   name:"Café Clock Fès",                      category:"restaurant", city:"Fès",        lat:34.0635,lng:-4.9815, rating:4.6,price:"$$", phone:"+212 535 63 78 55",address:"7 Derb el Magana, Talaa Kbira",      hours:"9:00-22:00"},
  {id:"fes_rest_2",   name:"Riad Rcif Restaurant",                category:"restaurant", city:"Fès",        lat:34.0660,lng:-4.9740, rating:4.5,price:"$$", phone:"+212 535 74 11 93",address:"Arset Bennis, Fès El Bali",          hours:"12:00-22:00"},
  {id:"fes_hosp_1",   name:"CHU Hassan II Fès",                   category:"hospital",   city:"Fès",        lat:34.0430,lng:-4.9720, phone:"+212 535 61 82 00",address:"Av. Hassan II, Fès",                 hours:"24/7"},
];

// ── Full UI translations (6 languages) ──
export const TRANSLATIONS = {
  fr:{
    navHome:"Accueil", navTicket:"Tickets", navSchedule:"Calendrier",
    themeToggle:"☀️ Clair", themeToggleDk:"🌙 Sombre", langLabel:"🌍 Langue",
    mobileHome:"🏠 Accueil", mobileTick:"🎟️ Tickets", mobileSch:"📅 Calendrier",
    heroBadge:"Coupe du Monde FIFA 2030",
    heroSub:"Votre guide ultime pour la Coupe du Monde FIFA 2030 au Maroc, Espagne et Portugal. Tout ce dont vous avez besoin, propulsé par IA.",
    heroFlags:"3 Pays · 6 Villes · 48 Équipes",
    heroBtn1:"Voir le calendrier", heroBtn2:"Acheter des billets", heroScroll:"Défiler",
    statTeams:"Équipes", statCities:"Villes hôtes", statCountries:"Pays", statMatches:"Matchs", statEdition:"Édition",
    secCities:"Villes Hôtes", secCitiesSub:"6 destinations emblématiques du Maroc",
    secMap:"Carte des Stades", secWeather:"Météo", secCurrency:"Convertisseur MAD",
    secNews:"Actualités", secInfo:"Infos Pratiques", secDarija:"Darija Essentiel",
    villeHote:"Ville hôte · Maroc",
    aiTitle:"Demandez à MoundiGuide AI",
    aiSub:"Votre compagnon de voyage intelligent pour la Coupe du Monde FIFA 2030",
    aiBtn:"Commencer à chatter",
    schBadge:"Coupe du Monde FIFA 2030", schTitle:"Calendrier des Matchs",
    schSub:"Tous les matchs · Juin – Juillet 2030",
    phAll:"Tous les matchs", phG:"Groupe", ph8:"8èmes", phQ:"Quarts", phS:"Demis", phF:"Finale",
    rankTitle:"Classement FIFA — 2026", newsTitle:"Dernières actualités",
    tickBadge:"Coupe du Monde FIFA 2030", tickTitle:"Billets",
    tickSub:"La billetterie FIFA officielle ouvre en janvier 2029. Voici tout ce que vous devez savoir.",
    tickCatTitle:"Catégories de billets", tickCatSub:"Prix indicatifs pour les matchs de groupe",
    tickStarting:"Prix de départ", tickHowTitle:"Comment acheter",
    tickInfoTitle:"Informations importantes",
    tickCTA:"Visiter FIFA.com pour les billets officiels",
    tickInfoItems:["Billets non-transférables, liés à votre ID FIFA","Vente officielle dès janvier 2029 sur FIFA.com","Revente uniquement via la plateforme officielle FIFA","Enfants de moins de 3 ans gratuits avec adulte payant","Places accessibles dans chaque catégorie","Billets numériques uniquement — via l'app mobile FIFA"],
    tickSteps:[{title:"Créer un compte FIFA",desc:"Inscrivez-vous sur FIFA.com. Vérification d'identité requise.",icon:"👤"},{title:"Sélectionner des matchs",desc:"Parcourez les matchs disponibles et choisissez vos préférés.",icon:"🏟️"},{title:"Choisir une catégorie",desc:"Choisissez parmi les catégories 1 à 4 selon votre budget.",icon:"🎟️"},{title:"Paiement sécurisé",desc:"Payez via le portail sécurisé FIFA. Billets numériques uniquement.",icon:"💳"}],
    footNav:"Navigation", footCountries:"Pays hôtes",
    footDesc:"Votre compagnon de voyage IA pour la Coupe du Monde FIFA 2030 au Maroc, Espagne et Portugal.",
    footRights:"© 2026 Moundi Guide · SUPMTI Rabat · Tous droits réservés",
    personalInfo:"Informations personnelles", firstName:"Prénom", lastName:"Nom", username:"Pseudo",
    saveChanges:"Sauvegarder", saved:"✓ Sauvegardé", favoriteTeam:"Équipe favorite",
    changeTeam:"Changer d'équipe", notifications:"Notifications", matchAlerts:"Alertes matchs",
    liveScores:"Scores en direct", teamNews:"Actualités équipe", preferences:"Préférences",
    language:"Langue", account:"Compte", changePassword:"🔑 Modifier le mot de passe",
    emailSent:"📧 Email envoyé !", deleteAccount:"Supprimer le compte", logout:"Se déconnecter",
    memberSince:"Membre depuis", backHome:"Accueil", photoUpdated:"✓ Photo mise à jour",
    saveAvatar:"📷 Enregistrer la photo", cancel:"Annuler",
    avatarFormatError:"Format non supporté (JPG, PNG, WebP)",
    avatarSizeError:"Image trop grande (max 5 Mo)",
    contactSupport:"Contactez le support pour supprimer votre compte.",
    confirmDelete:"Confirmer la suppression",
    starPlayers:"Joueurs Stars", tournament:"Tournoi 2026", group:"Groupe",
    viewMatches:"Voir les matchs", viewMap:"Carte des stades",
    worldCup2030:"Coupe du Monde FIFA 2026", qualified:"Qualifié",
    squad:"Hommes de match", matchStats:"Statistiques", comingSoon:"Données à venir",
    teamSheet:"Fiche Équipe",
    setupComplete:"Vous êtes prêt ! Bienvenue dans l'aventure Mondial 2030 🎉",
    chooseFavoriteTeam:"Choisissez votre équipe favorite",
    tellUsAboutYou:"Parlez-nous de vous",
    required:"Ce champ est obligatoire",
    notifStep:"Restez informé",
    notifSubtitle:"Recevez des alertes avant les matchs",
    activateNotif:"🔔 Activer les notifications",
    laterBtn:"Plus tard",
    manOfMatch:"Homme de match",
  },
  en:{
    navHome:"Home", navTicket:"Ticket", navSchedule:"Schedule",
    themeToggle:"☀️ Light", themeToggleDk:"🌙 Dark", langLabel:"🌍 Language",
    mobileHome:"🏠 Home", mobileTick:"🎟️ Ticket", mobileSch:"📅 Schedule",
    heroBadge:"FIFA World Cup 2030",
    heroSub:"Your ultimate guide for the 2030 FIFA World Cup in Morocco, Spain & Portugal. Everything you need, powered by AI.",
    heroFlags:"3 Countries · 6 Cities · 48 Teams",
    heroBtn1:"View Schedule", heroBtn2:"Get Tickets", heroScroll:"Scroll",
    statTeams:"Teams", statCities:"Host Cities", statCountries:"Countries", statMatches:"Matches", statEdition:"Edition",
    secCities:"Host Cities", secCitiesSub:"6 iconic Moroccan destinations",
    secMap:"Stadium Map", secWeather:"Weather", secCurrency:"MAD Converter",
    secNews:"News", secInfo:"Practical Info", secDarija:"Essential Darija",
    villeHote:"Host City · Morocco",
    aiTitle:"Ask MoundiGuide AI",
    aiSub:"Your intelligent travel companion for FIFA World Cup 2030",
    aiBtn:"Start Chatting",
    schBadge:"FIFA World Cup 2030", schTitle:"Match Schedule",
    schSub:"All matches · June – July 2030",
    phAll:"All Matches", phG:"Group Stage", ph8:"Round of 16", phQ:"Quarter-finals", phS:"Semi-finals", phF:"Final",
    rankTitle:"FIFA Rankings — 2026", newsTitle:"Latest News",
    tickBadge:"FIFA World Cup 2030", tickTitle:"Tickets",
    tickSub:"Official FIFA ticketing opens January 2029. Here's everything you need to know.",
    tickCatTitle:"Ticket Categories", tickCatSub:"Indicative prices for group stage matches",
    tickStarting:"Starting price", tickHowTitle:"How to Buy",
    tickInfoTitle:"Important Information",
    tickCTA:"Visit FIFA.com for Official Tickets",
    tickInfoItems:["Tickets are non-transferable and linked to your FIFA ID","Official sale opens January 2029 on FIFA.com","Resale only via official FIFA resale platform","Children under 3 enter free with a paying adult","Accessible seats available in every category","Digital tickets only — presented via FIFA mobile app"],
    tickSteps:[{title:"Create FIFA Account",desc:"Register at FIFA.com with your personal details. ID verification required.",icon:"👤"},{title:"Select Matches",desc:"Browse available matches and choose your preferred games and stadium.",icon:"🏟️"},{title:"Choose Category",desc:"Pick from Category 1–4 based on your budget and seat preference.",icon:"🎟️"},{title:"Secure Payment",desc:"Pay via FIFA secure portal. Tickets are digital — no physical tickets.",icon:"💳"}],
    footNav:"Navigation", footCountries:"Host Countries",
    footDesc:"Your AI-powered travel companion for the FIFA World Cup 2030 in Morocco, Spain & Portugal.",
    footRights:"© 2026 Moundi Guide · SUPMTI Rabat · All rights reserved",
    personalInfo:"Personal Information", firstName:"First Name", lastName:"Last Name", username:"Username",
    saveChanges:"Save Changes", saved:"✓ Saved", favoriteTeam:"Favorite Team",
    changeTeam:"Change Team", notifications:"Notifications", matchAlerts:"Match Alerts",
    liveScores:"Live Scores", teamNews:"Team News", preferences:"Preferences",
    language:"Language", account:"Account", changePassword:"🔑 Change Password",
    emailSent:"📧 Email sent!", deleteAccount:"Delete Account", logout:"Sign Out",
    memberSince:"Member since", backHome:"Home", photoUpdated:"✓ Photo updated",
    saveAvatar:"📷 Save Photo", cancel:"Cancel",
    avatarFormatError:"Unsupported format (JPG, PNG, WebP)",
    avatarSizeError:"File too large (max 5 MB)",
    contactSupport:"Contact support to delete your account.",
    confirmDelete:"Confirm deletion",
    starPlayers:"Star Players", tournament:"Tournament 2026", group:"Group",
    viewMatches:"View matches", viewMap:"Stadium map",
    worldCup2030:"FIFA World Cup 2026", qualified:"Qualified",
    squad:"Key players", matchStats:"Statistics", comingSoon:"Data coming soon",
    teamSheet:"Team Sheet",
    setupComplete:"You're all set! Welcome to the World Cup 2030 adventure 🎉",
    chooseFavoriteTeam:"Choose your favorite team",
    tellUsAboutYou:"Tell us about you",
    required:"This field is required",
    notifStep:"Stay informed",
    notifSubtitle:"Get alerts before matches",
    activateNotif:"🔔 Enable notifications",
    laterBtn:"Later",
    manOfMatch:"Key player",
  },
  ar:{
    navHome:"الرئيسية", navTicket:"التذاكر", navSchedule:"الجدول",
    themeToggle:"☀️ فاتح", themeToggleDk:"🌙 داكن", langLabel:"🌍 اللغة",
    mobileHome:"🏠 الرئيسية", mobileTick:"🎟️ التذاكر", mobileSch:"📅 الجدول",
    heroBadge:"كأس العالم FIFA 2030",
    heroSub:"دليلك الشامل لكأس العالم FIFA 2030 في المغرب وإسبانيا والبرتغال. كل ما تحتاجه، مدعوم بالذكاء الاصطناعي.",
    heroFlags:"٣ دول · ٦ مدن · ٤٨ فريقاً",
    heroBtn1:"عرض الجدول", heroBtn2:"احصل على التذاكر", heroScroll:"تمرير",
    statTeams:"فرق", statCities:"مدن مضيفة", statCountries:"دول", statMatches:"مباريات", statEdition:"نسخة",
    secCities:"المدن المضيفة", secCitiesSub:"٦ وجهات مغربية أيقونية",
    secMap:"خريطة الملاعب", secWeather:"الطقس", secCurrency:"تحويل الدرهم",
    secNews:"الأخبار", secInfo:"معلومات عملية", secDarija:"الدارجة الأساسية",
    villeHote:"مدينة مضيفة · المغرب",
    aiTitle:"اسأل MoundiGuide AI",
    aiSub:"رفيقك الذكي للسفر إلى كأس العالم FIFA 2030",
    aiBtn:"ابدأ المحادثة",
    schBadge:"كأس العالم FIFA 2030", schTitle:"جدول المباريات",
    schSub:"جميع المباريات · يونيو – يوليو 2030",
    phAll:"جميع المباريات", phG:"دور المجموعات", ph8:"دور الـ16", phQ:"ربع النهائي", phS:"نصف النهائي", phF:"النهائي",
    rankTitle:"تصنيف FIFA — 2026", newsTitle:"آخر الأخبار",
    tickBadge:"كأس العالم FIFA 2030", tickTitle:"التذاكر",
    tickSub:"تفتح بطاقات FIFA الرسمية في يناير 2029. إليك كل ما تحتاج لمعرفته.",
    tickCatTitle:"فئات التذاكر", tickCatSub:"أسعار استرشادية لمباريات دور المجموعات",
    tickStarting:"سعر البداية", tickHowTitle:"كيفية الشراء",
    tickInfoTitle:"معلومات مهمة",
    tickCTA:"زيارة FIFA.com للتذاكر الرسمية",
    tickInfoItems:["التذاكر غير قابلة للتحويل ومرتبطة بمعرف FIFA","البيع الرسمي يبدأ يناير 2029 على FIFA.com","إعادة البيع فقط عبر منصة FIFA الرسمية","الأطفال دون 3 سنوات يدخلون مجاناً مع بالغ","مقاعد ذوي الاحتياجات متاحة في كل فئة","تذاكر رقمية فقط — عبر تطبيق FIFA للجوال"],
    tickSteps:[{title:"إنشاء حساب FIFA",desc:"سجّل على FIFA.com بمعلوماتك الشخصية. التحقق من الهوية مطلوب.",icon:"👤"},{title:"اختر المباريات",desc:"تصفح المباريات المتاحة واختر ألعابك المفضلة.",icon:"🏟️"},{title:"اختر الفئة",desc:"اختر من الفئات 1-4 بناءً على ميزانيتك.",icon:"🎟️"},{title:"الدفع الآمن",desc:"ادفع عبر بوابة FIFA الآمنة. التذاكر رقمية.",icon:"💳"}],
    footNav:"التنقل", footCountries:"الدول المضيفة",
    footDesc:"رفيقك الذكي للسفر لكأس العالم FIFA 2030 في المغرب وإسبانيا والبرتغال.",
    footRights:"© 2026 Moundi Guide · SUPMTI الرباط · جميع الحقوق محفوظة",
    personalInfo:"المعلومات الشخصية", firstName:"الاسم", lastName:"اللقب", username:"اسم المستخدم",
    saveChanges:"حفظ التغييرات", saved:"✓ تم الحفظ", favoriteTeam:"الفريق المفضل",
    changeTeam:"تغيير الفريق", notifications:"الإشعارات", matchAlerts:"تنبيهات المباريات",
    liveScores:"النتائج المباشرة", teamNews:"أخبار الفريق", preferences:"التفضيلات",
    language:"اللغة", account:"الحساب", changePassword:"🔑 تغيير كلمة المرور",
    emailSent:"📧 تم إرسال البريد !", deleteAccount:"حذف الحساب", logout:"تسجيل الخروج",
    memberSince:"عضو منذ", backHome:"الرئيسية", photoUpdated:"✓ تم تحديث الصورة",
    saveAvatar:"📷 حفظ الصورة", cancel:"إلغاء",
    avatarFormatError:"تنسيق غير مدعوم (JPG, PNG, WebP)",
    avatarSizeError:"الملف كبير جداً (٥ ميغابايت كحد أقصى)",
    contactSupport:"تواصل مع الدعم لحذف حسابك.",
    confirmDelete:"تأكيد الحذف",
    starPlayers:"نجوم الفريق", tournament:"بطولة 2026", group:"المجموعة",
    viewMatches:"عرض المباريات", viewMap:"خريطة الملاعب",
    worldCup2030:"كأس العالم FIFA 2026", qualified:"مؤهل",
    squad:"أبطال المباراة", matchStats:"الإحصائيات", comingSoon:"البيانات قريباً",
    teamSheet:"بطاقة الفريق",
    setupComplete:"أنت جاهز! مرحباً بك في مغامرة كأس العالم 2030 🎉",
    chooseFavoriteTeam:"اختر فريقك المفضل",
    tellUsAboutYou:"أخبرنا عنك",
    required:"هذا الحقل مطلوب",
    notifStep:"ابق على اطلاع",
    notifSubtitle:"احصل على تنبيهات قبل المباريات",
    activateNotif:"🔔 تفعيل الإشعارات",
    laterBtn:"لاحقاً",
    manOfMatch:"رجل المباراة",
  },
  es:{
    navHome:"Inicio", navTicket:"Entradas", navSchedule:"Calendario",
    themeToggle:"☀️ Claro", themeToggleDk:"🌙 Oscuro", langLabel:"🌍 Idioma",
    mobileHome:"🏠 Inicio", mobileTick:"🎟️ Entradas", mobileSch:"📅 Calendario",
    heroBadge:"Copa del Mundo FIFA 2030",
    heroSub:"Tu guía definitiva para la Copa del Mundo FIFA 2030 en Marruecos, España y Portugal. Todo lo que necesitas, con IA.",
    heroFlags:"3 Países · 6 Ciudades · 48 Equipos",
    heroBtn1:"Ver calendario", heroBtn2:"Comprar entradas", heroScroll:"Desplazar",
    statTeams:"Equipos", statCities:"Ciudades", statCountries:"Países", statMatches:"Partidos", statEdition:"Edición",
    secCities:"Ciudades Sede", secCitiesSub:"6 destinos icónicos de Marruecos",
    secMap:"Mapa de Estadios", secWeather:"Tiempo", secCurrency:"Conversor MAD",
    secNews:"Noticias", secInfo:"Información Práctica", secDarija:"Darija Esencial",
    villeHote:"Ciudad Sede · Marruecos",
    aiTitle:"Pregunta a MoundiGuide AI",
    aiSub:"Tu compañero de viaje inteligente para la Copa del Mundo FIFA 2030",
    aiBtn:"Empezar a chatear",
    schBadge:"Copa del Mundo FIFA 2030", schTitle:"Calendario de Partidos",
    schSub:"Todos los partidos · Junio – Julio 2030",
    phAll:"Todos", phG:"Fase de Grupos", ph8:"Octavos", phQ:"Cuartos de Final", phS:"Semifinales", phF:"Final",
    rankTitle:"Ranking FIFA — 2026", newsTitle:"Últimas noticias",
    tickBadge:"Copa del Mundo FIFA 2030", tickTitle:"Entradas",
    tickSub:"La venta oficial de entradas FIFA abre en enero 2029. Aquí tienes todo lo que necesitas saber.",
    tickCatTitle:"Categorías de Entradas", tickCatSub:"Precios indicativos para fase de grupos",
    tickStarting:"Precio inicial", tickHowTitle:"Cómo comprar",
    tickInfoTitle:"Información importante",
    tickCTA:"Visitar FIFA.com para entradas oficiales",
    tickInfoItems:["Entradas intransferibles, vinculadas a tu ID FIFA","Venta oficial desde enero 2029 en FIFA.com","Reventa solo a través de la plataforma oficial FIFA","Niños menores de 3 años entran gratis con adulto","Asientos accesibles en cada categoría","Solo entradas digitales — via app móvil FIFA"],
    tickSteps:[{title:"Crear cuenta FIFA",desc:"Regístrate en FIFA.com con tus datos. Verificación de identidad requerida.",icon:"👤"},{title:"Seleccionar partidos",desc:"Explora los partidos disponibles y elige tus preferidos.",icon:"🏟️"},{title:"Elegir categoría",desc:"Elige entre Categoría 1-4 según tu presupuesto.",icon:"🎟️"},{title:"Pago seguro",desc:"Paga via portal seguro FIFA. Las entradas son digitales.",icon:"💳"}],
    footNav:"Navegación", footCountries:"Países Anfitriones",
    footDesc:"Tu compañero de viaje IA para la Copa del Mundo FIFA 2030 en Marruecos, España y Portugal.",
    footRights:"© 2026 Moundi Guide · SUPMTI Rabat · Todos los derechos reservados",
    personalInfo:"Información personal", firstName:"Nombre", lastName:"Apellido", username:"Usuario",
    saveChanges:"Guardar cambios", saved:"✓ Guardado", favoriteTeam:"Equipo favorito",
    changeTeam:"Cambiar equipo", notifications:"Notificaciones", matchAlerts:"Alertas de partidos",
    liveScores:"Marcadores en vivo", teamNews:"Noticias del equipo", preferences:"Preferencias",
    language:"Idioma", account:"Cuenta", changePassword:"🔑 Cambiar contraseña",
    emailSent:"📧 ¡Email enviado!", deleteAccount:"Eliminar cuenta", logout:"Cerrar sesión",
    memberSince:"Miembro desde", backHome:"Inicio", photoUpdated:"✓ Foto actualizada",
    saveAvatar:"📷 Guardar foto", cancel:"Cancelar",
    avatarFormatError:"Formato no soportado (JPG, PNG, WebP)",
    avatarSizeError:"Archivo demasiado grande (máx. 5 MB)",
    contactSupport:"Contacta al soporte para eliminar tu cuenta.",
    confirmDelete:"Confirmar eliminación",
    starPlayers:"Jugadores Estrella", tournament:"Torneo 2026", group:"Grupo",
    viewMatches:"Ver partidos", viewMap:"Mapa de estadios",
    worldCup2030:"Copa Mundial FIFA 2026", qualified:"Clasificado",
    squad:"Jugadores clave", matchStats:"Estadísticas", comingSoon:"Datos próximamente",
    teamSheet:"Ficha",
    setupComplete:"¡Listo! Bienvenido a la aventura del Mundial 2030 🎉",
    chooseFavoriteTeam:"Elige tu equipo favorito",
    tellUsAboutYou:"Cuéntanos sobre ti",
    required:"Este campo es obligatorio",
    notifStep:"Mantente informado",
    notifSubtitle:"Recibe alertas antes de los partidos",
    activateNotif:"🔔 Activar notificaciones",
    laterBtn:"Más tarde",
    manOfMatch:"Jugador clave",
  },
  pt:{
    navHome:"Início", navTicket:"Bilhetes", navSchedule:"Calendário",
    themeToggle:"☀️ Claro", themeToggleDk:"🌙 Escuro", langLabel:"🌍 Idioma",
    mobileHome:"🏠 Início", mobileTick:"🎟️ Bilhetes", mobileSch:"📅 Calendário",
    heroBadge:"Copa do Mundo FIFA 2030",
    heroSub:"O seu guia definitivo para a Copa do Mundo FIFA 2030 em Marrocos, Espanha e Portugal. Tudo o que precisa, com IA.",
    heroFlags:"3 Países · 6 Cidades · 48 Equipas",
    heroBtn1:"Ver calendário", heroBtn2:"Comprar bilhetes", heroScroll:"Rolar",
    statTeams:"Equipas", statCities:"Cidades", statCountries:"Países", statMatches:"Jogos", statEdition:"Edição",
    secCities:"Cidades Sede", secCitiesSub:"6 destinos icónicos de Marrocos",
    secMap:"Mapa dos Estádios", secWeather:"Tempo", secCurrency:"Conversor MAD",
    secNews:"Notícias", secInfo:"Informação Prática", secDarija:"Darija Essencial",
    villeHote:"Cidade Sede · Marrocos",
    aiTitle:"Pergunte ao MoundiGuide AI",
    aiSub:"O seu companheiro de viagem inteligente para a Copa do Mundo FIFA 2030",
    aiBtn:"Começar a conversar",
    schBadge:"Copa do Mundo FIFA 2030", schTitle:"Calendário de Jogos",
    schSub:"Todos os jogos · Junho – Julho 2030",
    phAll:"Todos", phG:"Fase de Grupos", ph8:"Oitavos", phQ:"Quartos de Final", phS:"Meias-finais", phF:"Final",
    rankTitle:"Ranking FIFA — 2026", newsTitle:"Últimas notícias",
    tickBadge:"Copa do Mundo FIFA 2030", tickTitle:"Bilhetes",
    tickSub:"A venda oficial de bilhetes FIFA abre em janeiro de 2029. Aqui está tudo o que precisa saber.",
    tickCatTitle:"Categorias de Bilhetes", tickCatSub:"Preços indicativos para fase de grupos",
    tickStarting:"Preço inicial", tickHowTitle:"Como comprar",
    tickInfoTitle:"Informação importante",
    tickCTA:"Visitar FIFA.com para bilhetes oficiais",
    tickInfoItems:["Bilhetes não transferíveis, ligados ao seu ID FIFA","Venda oficial abre janeiro 2029 em FIFA.com","Revenda apenas via plataforma oficial FIFA","Crianças menores de 3 anos entram gratuitamente","Lugares acessíveis disponíveis em cada categoria","Apenas bilhetes digitais — via app móvel FIFA"],
    tickSteps:[{title:"Criar conta FIFA",desc:"Registe-se em FIFA.com. Verificação de identidade necessária.",icon:"👤"},{title:"Selecionar jogos",desc:"Navegue pelos jogos disponíveis e escolha os seus preferidos.",icon:"🏟️"},{title:"Escolher categoria",desc:"Escolha entre Categoria 1-4 com base no seu orçamento.",icon:"🎟️"},{title:"Pagamento seguro",desc:"Pague via portal seguro FIFA. Bilhetes são digitais.",icon:"💳"}],
    footNav:"Navegação", footCountries:"Países Anfitriões",
    footDesc:"O seu companheiro de viagem IA para a Copa do Mundo FIFA 2030 em Marrocos, Espanha e Portugal.",
    footRights:"© 2026 Moundi Guide · SUPMTI Rabat · Todos os direitos reservados",
    personalInfo:"Informações pessoais", firstName:"Nome", lastName:"Sobrenome", username:"Nome de utilizador",
    saveChanges:"Guardar alterações", saved:"✓ Guardado", favoriteTeam:"Equipa favorita",
    changeTeam:"Mudar equipa", notifications:"Notificações", matchAlerts:"Alertas de jogos",
    liveScores:"Resultados ao vivo", teamNews:"Notícias da equipa", preferences:"Preferências",
    language:"Idioma", account:"Conta", changePassword:"🔑 Alterar senha",
    emailSent:"📧 Email enviado!", deleteAccount:"Eliminar conta", logout:"Terminar sessão",
    memberSince:"Membro desde", backHome:"Início", photoUpdated:"✓ Foto atualizada",
    saveAvatar:"📷 Guardar foto", cancel:"Cancelar",
    avatarFormatError:"Formato não suportado (JPG, PNG, WebP)",
    avatarSizeError:"Ficheiro demasiado grande (máx. 5 MB)",
    contactSupport:"Contacte o suporte para eliminar a sua conta.",
    confirmDelete:"Confirmar eliminação",
    starPlayers:"Jogadores Estrela", tournament:"Torneio 2026", group:"Grupo",
    viewMatches:"Ver jogos", viewMap:"Mapa de estádios",
    worldCup2030:"Copa do Mundo FIFA 2026", qualified:"Qualificado",
    squad:"Jogadores chave", matchStats:"Estatísticas", comingSoon:"Dados em breve",
    teamSheet:"Ficha",
    setupComplete:"Estás pronto! Bem-vindo à aventura do Mundial 2030 🎉",
    chooseFavoriteTeam:"Escolhe a tua equipa favorita",
    tellUsAboutYou:"Fala-nos de ti",
    required:"Este campo é obrigatório",
    notifStep:"Fica informado",
    notifSubtitle:"Recebe alertas antes dos jogos",
    activateNotif:"🔔 Ativar notificações",
    laterBtn:"Mais tarde",
    manOfMatch:"Jogador chave",
  },
  zh:{
    navHome:"首页", navTicket:"门票", navSchedule:"赛程",
    themeToggle:"☀️ 浅色", themeToggleDk:"🌙 深色", langLabel:"🌍 语言",
    mobileHome:"🏠 首页", mobileTick:"🎟️ 门票", mobileSch:"📅 赛程",
    heroBadge:"2030年FIFA世界杯",
    heroSub:"您的2030年FIFA世界杯终极指南，涵盖摩洛哥、西班牙和葡萄牙。一切所需，AI驱动。",
    heroFlags:"3个国家 · 6座城市 · 48支球队",
    heroBtn1:"查看赛程", heroBtn2:"购买门票", heroScroll:"滚动",
    statTeams:"球队", statCities:"主办城市", statCountries:"国家", statMatches:"场比赛", statEdition:"届",
    secCities:"主办城市", secCitiesSub:"摩洛哥6个标志性目的地",
    secMap:"球场地图", secWeather:"天气", secCurrency:"迪拉姆换算",
    secNews:"新闻", secInfo:"实用信息", secDarija:"基础达里贾语",
    villeHote:"主办城市 · 摩洛哥",
    aiTitle:"询问MoundiGuide AI",
    aiSub:"您的2030年FIFA世界杯智能旅行伴侣",
    aiBtn:"开始聊天",
    schBadge:"2030年FIFA世界杯", schTitle:"赛程表",
    schSub:"全部比赛 · 2030年6月–7月",
    phAll:"全部", phG:"小组赛", ph8:"十六强", phQ:"四分之一决赛", phS:"半决赛", phF:"决赛",
    rankTitle:"FIFA排名 — 2026", newsTitle:"最新消息",
    tickBadge:"2030年FIFA世界杯", tickTitle:"门票",
    tickSub:"FIFA官方购票将于2029年1月开放。以下是您需要了解的一切。",
    tickCatTitle:"门票类别", tickCatSub:"小组赛门票参考价格",
    tickStarting:"起步价", tickHowTitle:"如何购买",
    tickInfoTitle:"重要信息",
    tickCTA:"访问FIFA.com获取官方门票",
    tickInfoItems:["门票不可转让，与FIFA账号绑定","2029年1月在FIFA.com正式开售","仅可通过FIFA官方平台转售","3岁以下儿童与付费成人同行免费","每个类别均提供无障碍座位","仅限电子票 — 通过FIFA手机应用程序出示"],
    tickSteps:[{title:"创建FIFA账号",desc:"在FIFA.com注册您的个人信息。需要身份验证。",icon:"👤"},{title:"选择比赛",desc:"浏览可用比赛，选择您喜欢的场次。",icon:"🏟️"},{title:"选择类别",desc:"根据预算从第1-4类中选择。",icon:"🎟️"},{title:"安全支付",desc:"通过FIFA安全门户支付。门票为电子票。",icon:"💳"}],
    footNav:"导航", footCountries:"主办国",
    footDesc:"您的AI驱动旅行伴侣，服务于摩洛哥、西班牙和葡萄牙的2030年FIFA世界杯。",
    footRights:"© 2026 Moundi Guide · SUPMTI 拉巴特 · 保留所有权利",
    personalInfo:"个人信息", firstName:"名", lastName:"姓", username:"用户名",
    saveChanges:"保存更改", saved:"✓ 已保存", favoriteTeam:"最喜欢的球队",
    changeTeam:"更换球队", notifications:"通知", matchAlerts:"比赛提醒",
    liveScores:"实时比分", teamNews:"球队动态", preferences:"偏好设置",
    language:"语言", account:"账户", changePassword:"🔑 修改密码",
    emailSent:"📧 邮件已发送！", deleteAccount:"删除账户", logout:"退出登录",
    memberSince:"注册于", backHome:"首页", photoUpdated:"✓ 头像已更新",
    saveAvatar:"📷 保存头像", cancel:"取消",
    avatarFormatError:"不支持的格式（JPG、PNG、WebP）",
    avatarSizeError:"文件过大（最大5MB）",
    contactSupport:"联系客服以删除您的账户。",
    confirmDelete:"确认删除",
    starPlayers:"明星球员", tournament:"2026赛事", group:"小组",
    viewMatches:"查看比赛", viewMap:"场馆地图",
    worldCup2030:"2026年FIFA世界杯", qualified:"已晋级",
    squad:"关键球员", matchStats:"统计数据", comingSoon:"数据即将推出",
    teamSheet:"球队详情",
    setupComplete:"准备好了！欢迎来到2030世界杯之旅 🎉",
    chooseFavoriteTeam:"选择你最爱的球队",
    tellUsAboutYou:"告诉我们关于你",
    required:"此字段为必填项",
    notifStep:"保持关注",
    notifSubtitle:"比赛前获取提醒",
    activateNotif:"🔔 开启通知",
    laterBtn:"稍后",
    manOfMatch:"关键球员",
  },
};

export const CITY_GUIDE = {
  'New York': {
    country:'usa', flag:'🇺🇸',
    stadium:'MetLife Stadium',
    restaurants:[
      {name:'Laut',                 type:'🍜 Halal Asian',           price:'$$',  area:'Union Square'},
      {name:'Mamoun\'s Falafel',    type:'🥙 Halal Middle Eastern',  price:'$',   area:'Manhattan'},
      {name:'Burger & Lobster',     type:'🍔 American',              price:'$$$', area:'Midtown'},
    ],
    hotels:[
      {name:'The Jane Hotel',   stars:3, price:'$120/nuit', area:'West Village'},
      {name:'YOTEL New York',   stars:4, price:'$180/nuit', area:'Midtown'},
      {name:'Pod 51',           stars:3, price:'$100/nuit', area:'Midtown East'},
    ],
    transport:[
      'Metro (MTA) — billet $2.90, carnet $33',
      'Bus NJ Transit → MetLife Stadium depuis Penn Station',
      'Taxi/Uber disponibles 24h/24',
    ],
    fanZone:'Times Square Fan Zone — matchs sur écrans géants',
    emergency:{police:'911', hospital:'NYC Health + Hospitals', embassy:'Ambassade Maroc: +1 202 462 7979'},
    tips:'Achetez la MetroCard hebdomadaire ($33). Évitez les taxis non officiels.',
  },
  'Los Angeles': {
    country:'usa', flag:'🇺🇸',
    stadium:'SoFi Stadium',
    restaurants:[
      {name:'Zankou Chicken',   type:'🍗 Halal Armenian',  price:'$',   area:'Hollywood'},
      {name:'Bavel',            type:'🥙 Mediterranean',   price:'$$$', area:'Downtown'},
      {name:'In-N-Out Burger',  type:'🍔 American',        price:'$',   area:'Partout'},
    ],
    hotels:[
      {name:'Hotel Figueroa',       stars:4, price:'$160/nuit', area:'Downtown'},
      {name:'Freehand Los Angeles', stars:3, price:'$130/nuit', area:'Koreatown'},
      {name:'The LINE Hotel',       stars:4, price:'$200/nuit', area:'Koreatown'},
    ],
    transport:[
      'Metro LA — billet $1.75, pass journée $5',
      'Uber/Lyft — recommandé pour SoFi Stadium',
      'Location voiture conseillée pour se déplacer',
    ],
    fanZone:'LA Live Fan Village — proche Crypto.com Arena',
    emergency:{police:'911', hospital:'Cedars-Sinai Medical Center', embassy:'Consulat Maroc LA: +1 310 444 2900'},
    tips:'LA est très étendue — logez proche du métro. Réservez Uber à l\'avance les jours de match.',
  },
  'Dallas': {
    country:'usa', flag:'🇺🇸',
    stadium:'AT&T Stadium (Arlington)',
    restaurants:[
      {name:'Afrah Mediterranean', type:'🥙 Halal Mediterranean', price:'$$', area:'Richardson'},
      {name:'Pecan Lodge BBQ',     type:'🥩 Texas BBQ',           price:'$$', area:'Deep Ellum'},
      {name:'Al Basha',            type:'🧆 Halal Arab',          price:'$',  area:'Richardson'},
    ],
    hotels:[
      {name:'Omni Dallas Hotel',    stars:4, price:'$200/nuit', area:'Downtown'},
      {name:'Hyatt Regency Dallas', stars:4, price:'$180/nuit', area:'Downtown'},
      {name:'Aloft Dallas',         stars:3, price:'$130/nuit', area:'Uptown'},
    ],
    transport:[
      'DART Light Rail — billet $2.50',
      'Navette officielle FIFA depuis Downtown Dallas',
      'Location voiture recommandée',
    ],
    fanZone:'Dallas Fan Festival — Reunion Tower area',
    emergency:{police:'911', hospital:'Baylor University Medical Center', embassy:'Ambassade Maroc DC: +1 202 462 7979'},
    tips:'Températures élevées en juin (35°C+). Hydratez-vous. Portez de la crème solaire.',
  },
  'Miami': {
    country:'usa', flag:'🇺🇸',
    stadium:'Hard Rock Stadium',
    restaurants:[
      {name:'Casablanca Restaurant', type:'🥙 Marocain/Halal',  price:'$$',  area:'Little Havana'},
      {name:'Jaguar Restaurant',     type:'🍹 Latin American',  price:'$$$', area:'Coconut Grove'},
      {name:'Wynwood Kitchen',       type:'🍕 American',        price:'$$',  area:'Wynwood'},
    ],
    hotels:[
      {name:'Urbanica The Meridian',    stars:3, price:'$140/nuit', area:'South Beach'},
      {name:'Selina Gold Dust Miami',   stars:3, price:'$120/nuit', area:'Downtown'},
      {name:'SIXTY LES Hotel',          stars:4, price:'$220/nuit', area:'South Beach'},
    ],
    transport:[
      'Metrorail + Metromover gratuit Downtown',
      'Uber/Lyft très utilisés',
      'Bateau-taxi Brickell City Centre',
    ],
    fanZone:'Bayfront Park Fan Zone — bord de mer Miami',
    emergency:{police:'911', hospital:'Jackson Memorial Hospital', embassy:'Consulat Maroc Miami: +1 305 373 5300'},
    tips:'Humidité très élevée en juin. Logez à Brickell ou Downtown pour éviter la circulation.',
  },
  'Kansas City': {
    country:'usa', flag:'🇺🇸',
    stadium:'Arrowhead Stadium',
    restaurants:[
      {name:'Halal Guys KC',          type:'🥙 Halal Mediterranean', price:'$',  area:'Downtown'},
      {name:'Joe\'s Kansas City BBQ', type:'🥩 BBQ',                 price:'$$', area:'Mission'},
      {name:'Fiorella\'s Jack Stack', type:'🥩 BBQ',                 price:'$$', area:'Martin City'},
    ],
    hotels:[
      {name:'Hotel Kansas City', stars:4, price:'$150/nuit', area:'Downtown'},
      {name:'Crossroads Hotel',  stars:4, price:'$160/nuit', area:'Crossroads'},
      {name:'21c Museum Hotel',  stars:4, price:'$180/nuit', area:'Downtown'},
    ],
    transport:[
      'Streetcar KC — gratuit sur Main St',
      'Lyft/Uber pour Arrowhead Stadium',
      'Parking limité — navettes recommandées',
    ],
    fanZone:'Power & Light District Fan Zone',
    emergency:{police:'911', hospital:'KU Medical Center', embassy:'Ambassade Maroc DC: +1 202 462 7979'},
    tips:'Orages fréquents en juin. Prévoyez un imperméable.',
  },
  'Houston': {
    country:'usa', flag:'🇺🇸',
    stadium:'NRG Stadium',
    restaurants:[
      {name:'Al-Aseel Grill',        type:'🥙 Halal Lebanese', price:'$$', area:'Westheimer'},
      {name:'The Halal Guys Houston', type:'🥙 Halal',         price:'$',  area:'Midtown'},
      {name:'Killen\'s BBQ',         type:'🥩 Texas BBQ',      price:'$$', area:'Pearland'},
    ],
    hotels:[
      {name:'C. Baldwin Hotel',     stars:4, price:'$170/nuit', area:'Downtown'},
      {name:'Aloft Houston',        stars:3, price:'$130/nuit', area:'Midtown'},
      {name:'Hotel ZaZa Houston',   stars:4, price:'$200/nuit', area:'Museum District'},
    ],
    transport:[
      'METRORail — billet $1.25',
      'Navette officielle FIFA depuis Downtown',
      'Location voiture recommandée',
    ],
    fanZone:'Discovery Green Fan Zone — Houston Downtown',
    emergency:{police:'911', hospital:'Memorial Hermann Texas Medical Center', embassy:'Consulat Maroc Houston: +1 713 439 2422'},
    tips:'Chaleur et humidité extrêmes (38°C+). Restez hydratés. NRG Stadium est climatisé.',
  },
  'Mexico City': {
    country:'mexico', flag:'🇲🇽',
    stadium:'Estadio Azteca',
    restaurants:[
      {name:'El Cardenal',      type:'🌮 Mexican traditionnel', price:'$$',   area:'Centro Histórico'},
      {name:'Pujol',            type:'🍽 Gastronomique',        price:'$$$$', area:'Polanco'},
      {name:'Halal Food México', type:'🥙 Halal',              price:'$',    area:'Polanco'},
    ],
    hotels:[
      {name:'Hotel Carlota',              stars:4, price:'$120/nuit', area:'Cuauhtémoc'},
      {name:'Casa Decu',                  stars:3, price:'$80/nuit',  area:'Condesa'},
      {name:'Hyatt Regency Mexico City',  stars:5, price:'$200/nuit', area:'Polanco'},
    ],
    transport:[
      'Metro CDMX — billet 5 pesos (~0.25$)',
      'Metrobus — billet 6 pesos',
      'Uber disponible et économique',
    ],
    fanZone:'Zócalo Fan Zone — Place principale CDMX',
    emergency:{police:'911', hospital:'Hospital Ángeles Lomas', embassy:'Ambassade Maroc Mexico: +52 55 5596 3467'},
    tips:'Altitude 2240m — acclimatez-vous 1-2 jours. Évitez l\'eau du robinet. Uber est sûr et pas cher.',
  },
  'Guadalajara': {
    country:'mexico', flag:'🇲🇽',
    stadium:'Estadio Akron',
    restaurants:[
      {name:'La Chata',              type:'🌮 Mexican tapatío', price:'$',  area:'Centro'},
      {name:'Karne Garibaldi',       type:'🥩 Birria',         price:'$$', area:'Zapopan'},
      {name:'Restaurant Halal GDL',  type:'🥙 Halal',          price:'$',  area:'Zapopan'},
    ],
    hotels:[
      {name:'One Guadalajara Tapatío', stars:3, price:'$70/nuit',  area:'Tapatío'},
      {name:'Hilton Guadalajara',      stars:5, price:'$160/nuit', area:'Centro'},
      {name:'Hampton Inn Zapopan',     stars:3, price:'$90/nuit',  area:'Zapopan'},
    ],
    transport:[
      'Tren Ligero (tramway) — billet 9 pesos',
      'Uber recommandé pour Estadio Akron',
      'Macrobús — réseau bus rapide',
    ],
    fanZone:'Zapopan Fan Village — près du stade',
    emergency:{police:'911', hospital:'Hospital Country 2000', embassy:'Ambassade Maroc Mexico: +52 55 5596 3467'},
    tips:'Ville très sûre. Climat agréable. Tequila et birria — spécialités locales à goûter!',
  },
  'Toronto': {
    country:'canada', flag:'🇨🇦',
    stadium:'BMO Field',
    restaurants:[
      {name:'Paramount Fine Foods',        type:'🥙 Halal Lebanese', price:'$$',   area:'Multiple locations'},
      {name:'Ali Baba\'s Middle Eastern',  type:'🥙 Halal',          price:'$',    area:'Downtown'},
      {name:'Canoe Restaurant',            type:'🍁 Canadian',       price:'$$$$', area:'Financial District'},
    ],
    hotels:[
      {name:'Gladstone House',                 stars:4, price:'$160/nuit', area:'West Queen West'},
      {name:'Ace Hotel Toronto',               stars:4, price:'$200/nuit', area:'Waverley'},
      {name:'Holiday Inn Toronto Downtown',    stars:3, price:'$140/nuit', area:'Downtown'},
    ],
    transport:[
      'TTC Subway — billet $3.30 CAD',
      'Streetcar 509 → BMO Field direct',
      'Presto Card recommandée (carte rechargeable)',
    ],
    fanZone:'Nathan Phillips Square Fan Zone',
    emergency:{police:'911', hospital:'Toronto General Hospital', embassy:'Ambassade Maroc Ottawa: +1 613 236 7391'},
    tips:'Très multiculturel — nombreux restaurants halal. Réservez tôt — hébergements limités.',
  },
  'Vancouver': {
    country:'canada', flag:'🇨🇦',
    stadium:'BC Place',
    restaurants:[
      {name:'Jamjar Canteen',   type:'🥙 Halal Lebanese', price:'$$',  area:'Commercial Drive'},
      {name:'Medina Café',      type:'☕ Brunch',          price:'$$',  area:'Downtown'},
      {name:'Ask for Luigi',    type:'🍝 Italian',         price:'$$$', area:'Railtown'},
    ],
    hotels:[
      {name:'Skwachàys Lodge', stars:4, price:'$180/nuit', area:'Downtown Eastside'},
      {name:'Victorian Hotel', stars:3, price:'$130/nuit', area:'Downtown'},
      {name:'Listel Hotel',    stars:4, price:'$200/nuit', area:'West End'},
    ],
    transport:[
      'SkyTrain — billet $3.15 CAD',
      'Compass Card — carte rechargeable recommandée',
      'BC Place accessible à pied depuis Downtown',
    ],
    fanZone:'Jack Poole Plaza Fan Zone — waterfront',
    emergency:{police:'911', hospital:'Vancouver General Hospital', embassy:'Ambassade Maroc Ottawa: +1 613 236 7391'},
    tips:'Ville magnifique. Pluie possible en juin. BC Place est à 10min à pied du centre.',
  },
};

// ── Helper functions ──
export function haversine(lat1,lng1,lat2,lng2){
  const R=6371000,dLat=(lat2-lat1)*Math.PI/180,dLng=(lng2-lng1)*Math.PI/180;
  const a=Math.sin(dLat/2)**2+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLng/2)**2;
  return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));
}
export function normalize(s){return s.normalize("NFD").replace(/[̀-ͯ]/g,"").toLowerCase();}
export function formatDist(m){return m<1000?`${Math.round(m)}m`:`${(m/1000).toFixed(1)}km`;}

export const F = "'Outfit'";
